nelmio_api_doc:
    documentation:
        info:
            title: Scheduler API
            description: API for schedule lessons in Far East Math Center
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
